blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name= "blog"

urlpatterns = [
    path("", render_posts, name='posts'),
    path("<int:post_id>", post_detail,
        name="post_detail")
]

django_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import urls

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
                                 

blog/models.py
from django.db import models
import datetime
from cloudinary.models import CloudinaryField
class Post(models.Model):
    title=models.CharField(max_length=100)
    description = models.TextField()
    image = CloudinaryField('image')
    date = models.DateTimeField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from cloudinary.models import CloudinaryField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = CloudinaryField('image')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
def render_posts(request):
    articulos = Post.objects.all()
    return render(request,'posts.html',{'posts':articulos})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request,'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,'home.html' , {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}

<div class="container py-5">
  <div class="text-center">
    <h1 class="display-4">{{post.title}}</h1>
    <h2 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h2>
  </div>
  <div class="content my-4">
    <p class="lead text-justify">{{post.description|safe}}</p>
  </div>
  <div class="text-center my-4">
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid rounded" style="max-width: 100%; height: auto;">
  </div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

<!-- Título de la Página -->
<h1 class="fs-2">Posts</h1>
<!-- Información de la Página (Segundo Titulo) -->
<h3>Noticias del {{ total_posts }} mes {{ total_posts|pluralize }}</h3>

{% for post in posts %}

<div class="py-3">

  <div class="card card-body bg-white">
    <div class="row">

      <!-- Columna para la imagen -->
      <div class="col-3">
        <img class="img-fluid" src="{{ post.image.url }}" alt="{{ post.title }}">
      </div>

      <!-- Columna para el contenido del post -->
      <div class="col-9">
        <!-- Título del post -->
        <h1>{{ post.title }}</h1>
        <!-- Descripción del post, se elimina el HTML y se limita a 400 caracteres -->
        <p>{{ post.description|striptags|truncatechars:400 }}</p>
        <!-- Fecha del post en formato especificado y en mayúsculas -->
        <p>{{ post.date|date:'F jS Y'|upper }}</p>
        <!-- Enlace al detalle del post -->
        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">Seguir Leyendo</a>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<!-- Sección de encabezado con imagen de perfil e introducción -->
<header class="row bg-white">
   <!-- Imagen de perfil -->
   <div class="col-md-4">
      <img src="{% static 'perfil.jpg' %}" alt="Perfil" width="350" height="350">
   </div>

   <!-- Texto de Introducción -->
   <div class="col-md-8 my-auto">
      <h1><strong> Somos Anthony Pico y Juan Vera</strong></h1>
      <h3>Estudiantes de la ULEAM</h3>
      <p>Hola a todos, nuestros nombres son Pico Baque Anthony Jordano/Vera Guerrero Juan Alejandro, somos estudiantes de la Universidad Laica Eloy Alfaro de Manabí, actualmente cursando el tercer semestre de la carrera de Ingeniería en Tecnologías de Información. Estamos emocionados de tener la oportunidad de compartir con ustedes nuestro proyecto para la asignatura de Análisis y Diseño de Base de Datos. Este proyecto se centra en la creación de una aplicación de navegación entre páginas utilizando Django, un framework de desarrollo web en Python, con el fin de demostrar el uso efectivo de vistas y navegación dentro de una aplicación web.</p>
      <!-- Botón para descargar el CV -->
      <a href="{% static 'curriculum.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
   </div>
</header>

<!-- Sección de Películas Favoritas -->
<div class="row my-4 text-center">
   <h1>Películas Favoritas (Horror/Suspenso)</h1>
   <p>Además de nuestro interés por la tecnología, tenemos una pasión por el cine de terror. Nos fascina cómo este género puede sumergirnos en mundos oscuros y perturbadores, desafiando nuestras percepciones y despertando emociones intensas. En nuestro tiempo libre, disfrutamos explorando películas que nos mantengan al borde del asiento con su suspenso y atmósfera inquietante. Estamos emocionados de compartir con ustedes algunas de nuestras películas favoritas:</p>
   
   <!-- Navegar sobre la lista de proyectos (películas favoritas) -->
   {% for project in projects %}
   <div class="col-md-4 p-4">
      <div class="card bg-white card-project">
         <!-- Imagen de la película -->
         <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top"/>
         <div class="card-body">
            <!-- Título y descripción de la película -->
            <h2>{{project.title}}</h2>
            <p>{{project.description}}</p>  
            <br>    
            <!-- Enlaces -->
            {% if project.url %}
                  <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
            {% endif %}
         </div>
      </div>
   </div>
   {% endfor %}
</div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'main.css' %}">
</head>
<body>
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
    {% block content %}
    {% endblock %}      
    </div>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">AnthonyPico/JuanVera</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'curriculum.pdf' %}" target="_blank">
                Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>